groups:
  - name: app-alerts
    rules:
      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) * 100 > 5
        for: 5m
        labels:
          severity: warning
          environment: ${environment}
        annotations:
          summary: High error rate detected
          description: Error rate is above 5% for the last 5 minutes

      - alert: HighLatency
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 1
        for: 5m
        labels:
          severity: warning
          environment: ${environment}
        annotations:
          summary: High latency detected
          description: Response time is above 1 second for the last 5 minutes

      - alert: HighCPUUsage
        expr: container_cpu_usage_seconds_total{container=~"frontend|backend"} > 0.8
        for: 5m
        labels:
          severity: warning
          environment: ${environment}
        annotations:
          summary: High CPU usage detected
          description: CPU usage is above 80% for the last 5 minutes

      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes{container=~"frontend|backend"} / container_spec_memory_limit_bytes{container=~"frontend|backend"} * 100 > 80
        for: 5m
        labels:
          severity: warning
          environment: ${environment}
        annotations:
          summary: High memory usage detected
          description: Memory usage is above 80% for the last 5 minutes

      - alert: PodRestart
        expr: kube_pod_container_status_restarts_total{container=~"frontend|backend"} > 0
        for: 1m
        labels:
          severity: warning
          environment: ${environment}
        annotations:
          summary: Pod restart detected
          description: Container has restarted in the last minute

      - alert: DeploymentFailed
        expr: kube_deployment_status_condition{type="Available", status="False"} == 1
        for: 5m
        labels:
          severity: critical
          environment: ${environment}
        annotations:
          summary: Deployment failed
          description: Deployment is not available for more than 5 minutes 